# Generated by Django 3.0 on 2021-03-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210303_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.IntegerField(default=18),
        ),
    ]
